pipeline {
    agent any

    parameters {
        string(name: 'DOCKER_IMAGE_VERSION', defaultValue: '', description: 'Docker Image Version')
        string(name: 'DID_BUILD_JAVA', defaultValue: '', description: 'Java Builded boolean')
        string(name: 'DID_BUILD_PYTHON', defaultValue: '', description: 'Python Builded boolean')
    }

    
    stages {
        stage('Checkout Main Branches') {
            steps {
                sh 'git checkout main'
                echo "DOCKER_IMAGE_VERSION: ${params.DOCKER_IMAGE_VERSION}"
                echo "DID_BUILD_JAVA: ${params.DID_BUILD_JAVA}"
                echo "DID_BUILD_PYTHON: ${params.DID_BUILD_PYTHON}"
            }
        }

        stage('update Python deploy.yaml') {
            when {
                expression {
                    return params.DID_BUILD_PYTHON == "true"
                }
            }

            steps {
                // Jenkins 파이프라인에서 작업 디렉터리를 변경할 때 사용한다.
                dir('python') {
                    sh 'pwd'
                    sh 'ls -al'
                    echo "Received Docker Image Version : ${params.DOCKER_IMAGE_VERSION}"
                    sh 'git checkout main'
                    sh "sed -i 's|viroovr/specguard-nlp:.*|viroovr/specguard-nlp:${params.DOCKER_IMAGE_VERSION}|g' deploy.yaml"
                    sh 'cat deploy.yaml'
                }
            }
        }

        stage('update Java deploy.yaml') {
            when {
                expression {
                    return params.DID_BUILD_JAVA == "true"
                }
            }

            steps {
                // Jenkins 파이프라인에서 작업 디렉터리를 변경할 때 사용한다.
                dir('java') {
                    sh 'pwd'
                    sh 'ls -al'
                    echo "Received Docker Image Version : ${params.DOCKER_IMAGE_VERSION}"
                    sh 'git checkout main'
                    sh "sed -i 's|viroovr/specguard-api:.*|viroovr/specguard-api:${params.DOCKER_IMAGE_VERSION}|g' deploy.yaml"
                    sh 'cat deploy.yaml'
                }
            }
        }

        stage('Commit & Push') {
            when {
                expression {
                    return params.DID_BUILD_PYTHON == "true" || params.DID_BUILD_JAVA == "true"
                }
            }

            steps {
                sh 'git config --list'
                sh 'git config user.name "viroovr"'
                sh 'git config user.email "tjgusdnjs789@gmail.com"'
                sh 'git config --list'
                sh 'git add .'
                sh "git commit -m '[Feat] update image version ${params.DOCKER_IMAGE_VERSION}'"
                sh 'git status'

                sshagent(['specguard-k8s-manifests']) {
                    sh 'git push'
                }
            }
        }
    }
}
