apiVersion: apps/v1
kind: Deployment
metadata:
  name: specguard-api
  namespace: specguard
  labels:
    app: specguard-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: specguard-api
  template:
    metadata:
      labels:
        app: specguard-api
    spec:
      containers:
      - name: specguard-api
        image: viroovr/specguard-api:2
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secrets