apiVersion: apps/v1
kind: Deployment
metadata:
  name: specguard-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: specguard-api
  template:
    metadata:
      labels:
        app: specguard-api
    spec:
      containers:
      - name: specguard-api
        image: viroovr/specguard-api:3
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1024Mi"
            cpu: "2"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secrets