apiVersion: v1
kind: Service
metadata:
  name: specguard-api-service
spec:
  type: ClusterIP
  selector:
    app: specguard-api
  ports:
  - name: specguard-api-port
    port: 8080
    targetPort: 8080
