apiVersion: apps/v1
kind: Deployment
metadata:
  name: specguard-nlp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: specguard-nlp-api
  template:
    metadata:
      labels:
        app: specguard-nlp-api
    spec:
      containers:
      - name: specguard-nlp
        image: viroovr/specguard-nlp:a4e574ac6c71779d32d09fb4a027716360068329
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: backend-config
          - secretRef:
              name: backend-secrets