apiVersion: v1
kind: Service
metadata:
  name: specguard-nlp-service
spec:
  type: ClusterIP
  selector:
    app: specguard-nlp-api
  ports:
  - name: specguard-nlp-port
    port: 8000
    targetPort: 8000
